### ISSUE TITLE
UTF-16の読み書きでBOMが欠落して文字化けが生じる

### ISSUE THREAD

**Issue by KeiBontakun** [kohii/smoothcsv#2]
はじめまして、とても重宝させていただいています。
Unicode(UTF-16)のCSVの読み書きで問題を見つけました。
本アプリはファイルの書き出し時にBOMをつけていないため、書き出されたCSVをSmoothCSV自身を含むアプリで再度開くとエンコーディングを判定できず文字化けが発生します。

検証手順：
1. CSVを何かUTF-16 BOM付で作成する
2. SmoothCSVで読み込んでどこか編集して保存する
3. エンコーディングのわかるエディタ（サクラエディタなど）で開くとBOMのサインが消えている
4. SmoothCSVで読み込むと文字化けが生じる

お役に立ちますでしょうか。

**Comment by kohii** [comment]
返信大変遅くなりまして申し訳ありません。
ご報告ありがとうございます。次回のリリースで対応を検討します。

**Comment by kohii** [comment]
v2.0.0-beta5にて修正しました。
エンコーディングを
- UTF16BE
- UTF16BE (BOMあり)
- UTF16LE
- UTF16LE (BOMあり)
の4種類に整理しました。

**Comment by KeiBontakun** [comment]
β版で修正が確認できました。ありがとうございます。
