### ISSUE TITLE
テキスト編集エリアでUp/Downキーが効かない

### ISSUE THREAD

**Issue by tani-ro-hei** [kohii/smoothcsv#3]
初めまして、いつも有り難く利用させていただいております。
既知でしたら申し訳ありませんが、以前のバージョンからbeta4まで、ウインドウ上部のテキスト編集エリアでUp/Downキーが効かないです。改行を含んだフィールドで上下キーでカーソルを動かそうとすると、「Error」とだけ書かれたダイアログが出ます。Left/Rightキーは正常に使えます。
環境は Windows 10 Home / x64 です。コード解析したりしておりませんので、はなはだ役に立たないコメントですが、よろしくお願いします。

**Comment by kohii** [comment]
ご報告ありがとうございます！
調査/修正いたします。

**Comment by kohii** [comment]
v2.0.0-beta5にて修正しました。
