### ISSUE TITLE
IMEの変換候補を移動すると高CPU負荷が生じる

### ISSUE THREAD

**Issue by tani-ro-hei** [kohii/smoothcsv#5]
お世話になっております。また入力まわりですが1件報告させて頂きます。環境は前回同様で、Windows 10 Home / x64 / Core i5-8400 です。
ふだんGoogle日本語入力を利用していますが、テキスト編集エリアで日本語変換する際、とりわけ最初の変換候補から次の変換候補へキーで移動しようとするタイミングで、数十秒単位のフリーズが生じ、悪くするとクラッシュします(悪くしなければ、何もせず待っていると変換されて復帰します)。リソースモニタを確認すると、そのタイミングでCPU負荷が急騰しており、Java(TM) Platform SE binary のプロセスで100%占有されるコアも出ているようでした。
Microsoft IME に切替えてみたところ、Google日本語入力ほど相性は悪くないようですが、やはりそのタイミングで負荷が生じてフリーズすることがあります。IMEの方が悪いのかもしれず、曖昧な話で恐縮なのですが、再現性のある現象のように見えるので、とりあえず報告させて頂きます。

**Comment by kohii** [comment]
返信大変遅くなりまして申し訳ありません。
調査いたしますので少々お待ち下さい。

**Comment by kohii** [comment]
v2.0.0-beta8で修正しました。
大変遅くなりまして申し訳ありません。
