### ISSUE TITLE
Shift_JISのファイルが文字化けする

### ISSUE THREAD

**Issue by ak-kn** [kohii/smoothcsv#6]
はじめまして。日頃ありがたく利用させていただいています。
Shift_JISのファイルで一部の文字が文字化けしてしまうようでして、「髙」などの旧字体や、「Ⅲ」「㎝」などの機種依存文字が該当します。
利用環境はWin10 Pro x64、バージョンはv2.0.0-beta6で、以前のバージョンでも同様だったかは確認できていません。
なお 旧SmoothCSV(Version1.0.7)では問題ないようです。
お手すきの際にご確認いただけましたら、甚だ幸いです。

**Comment by kitora** [comment]
横から失礼を。
この場合、文字コードで指定すべきは"Shift_JIS"ではなく、"windows-31j"ではないでしょうか？

**Comment by ak-kn** [comment]
ご指摘ありがとうございます。
なるほどと思い試してみたのですが、文字コードにwindows-31jを指定すること自体ができませんでした。

別の問題のように思われるためここで言及すべきではないかもしれませんが…。
ファイルを開く際の文字コードのプルダウンで「その他」を選び、
(a) 表示される文字コード一覧から「windows-31j」をクリックする
(b) 表示される入力欄に「windows-31j」と入力してEnterキーを押す

上記いずれの操作でも、文字コードのプルダウン選択肢が初期状態（＝自動判定）のままとなってしまいます。
試しにその状態でファイルを開いてみても、文字化けは解決しない（windows-31j指定で開けてはいない）状況です。

なお 旧SmoothCSV(Version1.0.7)では「その他」から他から任意の文字コードを指定することができ、Shift_JIS、windows-31jのいずれを指定した場合も、文字化けすることなくファイルを開くことができています。

**Comment by kohii** [comment]
@ak-kn 返信遅くなりまして申し訳ありません。
@kitora フォローありがとうございます。

@kitora さんの言及されている通り、windows-31jで開けば文字化けは解消されると思います。
（SmoothCSV1ではShift_JISを選択したときには内部的にwindows-31jに置き換えてファイルを読み込んでいます。）

文字コードを正しく選択できないのは不具合なので修正いたします。
少々お待ち下さい🙇‍♂️

**Comment by kohii** [comment]
@ak-kn 
遅くなりましたが、`2.0.0-beta7`のリリースにて対応しました。
https://github.com/kohii/smoothcsv/releases/tag/v2.0.0-beta7

- 文字コード選択の不具合を修正
- 文字コードの名前を修正
    - `Shift_JIS` → `Shift_JIS (Original)`
    - `windows-31j` → `Shift_JIS (MS932)`
- 文字コード自動判定時には`Shift_JIS (Original)`ではなく`Shift_JIS (MS932)`を優先して使用する
