### ISSUE TITLE
列挿入後に列名指定を解除すると右側が消える

### ISSUE THREAD

**Issue by tani-ro-hei** [kohii/smoothcsv#7]
CSVを開いて「テーブル＞1行目を列名として扱う」によってヘッダ行を固定した後、空列を挿入します。「1行目を列名として扱う」を解除すると、挿入列より右側のヘッダ内容が消え、そこで改行されて右側は灰色のセルになります。

**Comment by kohii** [comment]
不具合のご報告ありがとうございます。
v2.0.0-beta8で修正しました。
