### ISSUE TITLE
macOS Catalina Beta 10.5.5 でクラッシュ

### ISSUE THREAD

**Issue by masato-igarashi** [kohii/smoothcsv#8]
※OSレベルの不具合のようで、macOSをアップデートした後改善いたしました。
申し訳ありませんでした。

Version: v2.0.0-beta8 (macOS)
Java for Mac OS X Version 8 Update 251
macOS Catalina Beta 10.5.5環境にアップデート後、csvファイルをSmoothCSVで開き、横(列)方向のスクロールバーをドラッグしようとすると、100%で強制終了するようになってしまいました。

**Comment by kohii** [comment]
ご報告ありがとうございます！
承知しました。
