### ISSUE TITLE
Shift + Home does not work in cell edit mode

### ISSUE THREAD

**Issue by asiwjp** [kohii/smoothcsv#9]
セルにテキストが設定済みの状態で、F2->Shift+Homeでセル内のテキストを全選択しようとすると、
セルの編集状態が解除され、セル選択範囲が拡張されます。

**Comment by kohii** [comment]
Sorry for leaving this issue unattended for a long time.
Please use the latest version of SmoothCSV (3.0.0).

https://github.com/kohii/smoothcsv3
